"""Export the module structure with docstrings to a tree diagram file.

Scans a Python package directory, builds a tree of module names with first-line
module docstrings, and writes the result to an output file using Unicode
box-drawing characters.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

BRANCH = "├── "
LAST_BRANCH = "└── "
PIPE = "│   "
SPACE = "    "

# Relative paths (from the source root) to exclude from the tree and strict
# enforcement.
AUTO_EXCLUDED = {
    "_version.py",  # These are typically generated by dynamic VCS-based versioning tools.
}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export module structure with docstrings to a tree diagram.",
    )
    parser.add_argument(
        "--source-root",
        required=True,
        help="Path to the root package directory to scan.",
    )
    parser.add_argument(
        "--output-file",
        required=True,
        help="Path to the output file to write the tree diagram to.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        default=False,
        help="Fail if any module is missing a docstring.",
    )
    args = parser.parse_args()

    source_root = Path(args.source_root)
    output_file = Path(args.output_file)

    if not source_root.is_dir():
        print(f"ERROR: Source root {source_root} is not a directory.", file=sys.stderr)
        return 1

    init_path = source_root / "__init__.py"
    if not init_path.is_file():
        print(
            f"ERROR: {source_root} is not a Python package (no __init__.py).",
            file=sys.stderr,
        )
        return 1

    # Build the tree.
    missing: list[Path] = []
    root_name = source_root.name
    root_docstring = _get_first_docstring_line(init_path)
    if root_docstring is None:
        missing.append(init_path)
    root_comment = f"# {root_docstring}" if root_docstring else ""
    root_pair = (root_name, root_comment)

    child_pairs = _build_tree(source_root, "", missing, source_root)
    all_pairs = [root_pair, *child_pairs]

    # Align comments: pad each line so comments start at the same column.
    max_width = max(len(text) for text, _ in all_pairs)
    formatted: list[str] = []
    for text, comment in all_pairs:
        if comment:
            formatted.append(f"{text:<{max_width}}  {comment}")
        else:
            formatted.append(text)
    content = "\n".join(formatted) + "\n"

    try:
        existing = output_file.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None

    modified = content != existing
    if modified:
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(content, encoding="utf-8")
        print(f"Module tree written to {output_file}.")
    else:
        print("Module tree is already up to date.")

    if args.strict and missing:
        print(
            f"ERROR: {len(missing)} module(s) missing a docstring:",
            file=sys.stderr,
        )
        for path in missing:
            print(f"  - {path}", file=sys.stderr)
        return 1

    return 1 if modified else 0


def _get_first_docstring_line(path: Path) -> str | None:
    """Return the first line of the module docstring, or None if absent."""
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return None
    docstring = ast.get_docstring(tree)
    if docstring is None:
        return None
    return docstring.split("\n")[0].strip()


def _build_tree(
    root: Path,
    prefix: str,
    missing: list[Path],
    source_root: Path,
) -> list[tuple[str, str]]:
    """Recursively build tree lines for a package directory.

    Returns a list of (line_text, comment) pairs so the caller can align
    comments vertically.
    """
    lines: list[tuple[str, str]] = []

    # Collect .py files (excluding __init__.py) and subpackages.
    py_files: list[Path] = []
    subpackages: list[Path] = []

    for entry in sorted(root.iterdir()):
        if entry.name in ("__pycache__", "py.typed"):
            continue
        if entry.relative_to(source_root).as_posix() in AUTO_EXCLUDED:
            continue
        if entry.is_file() and entry.suffix == ".py" and entry.name != "__init__.py":
            py_files.append(entry)
        elif entry.is_dir() and (entry / "__init__.py").is_file():
            subpackages.append(entry)

    entries: list[Path] = [*py_files, *subpackages]
    if not entries:
        return lines

    for i, entry in enumerate(entries):
        is_last = i == len(entries) - 1
        connector = LAST_BRANCH if is_last else BRANCH
        child_prefix = prefix + (SPACE if is_last else PIPE)

        if entry.is_file():
            name = entry.stem
            docstring = _get_first_docstring_line(entry)
            if docstring is None:
                missing.append(entry)
            line_text = f"{prefix}{connector}{name}"
            comment = f"# {docstring}" if docstring else ""
            lines.append((line_text, comment))
        else:
            # Subpackage directory — attribute __init__.py docstring to the dir.
            name = entry.name
            init_path = entry / "__init__.py"
            docstring = _get_first_docstring_line(init_path)
            if docstring is None:
                missing.append(init_path)
            line_text = f"{prefix}{connector}{name}"
            comment = f"# {docstring}" if docstring else ""
            lines.append((line_text, comment))
            lines.extend(_build_tree(entry, child_prefix, missing, source_root))

    return lines


if __name__ == "__main__":
    raise SystemExit(main())
