"""Export public functions with docstrings from Python source files to a reference file.

Scans all Python source files under ``--source-root`` for public functions with a
docstring and writes a flat markdown bullet list to an output file.  Functions are
listed in the order they appear in each source file; files are processed in sorted
order.  Functions without a docstring are silently skipped unless ``--strict`` is
passed, in which case the hook fails and reports them.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

# Relative paths (from the source root) to exclude from scanning and strict
# enforcement.
AUTO_EXCLUDED = {
    "_version.py",  # Typically generated by dynamic VCS-based versioning tools.
}


def _module_name(source_file: Path, source_root: Path) -> str:
    """Derive a dotted module name from a file path relative to the source root."""
    rel = source_file.relative_to(source_root)
    parts = rel.with_suffix("").parts
    return ".".join(parts)


def _collect_source_files(source_root: Path) -> list[Path]:
    """Collect all .py files under *source_root*, sorted and filtered."""
    return sorted(
        p
        for p in source_root.rglob("*.py")
        if p.name != "__init__.py"
        and p.relative_to(source_root).as_posix() not in AUTO_EXCLUDED
    )


def _get_public_functions(
    path: Path,
) -> list[tuple[str, str | None]]:
    """Return (name, first_docstring_line_or_None) for each public function.

    All module-level public functions are returned in source order.
    """
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        print(f"ERROR: Cannot read {path}: {exc}", file=sys.stderr)
        return []

    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        print(f"ERROR: Cannot parse {path}: {exc}", file=sys.stderr)
        return []

    results: list[tuple[str, str | None]] = []
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_"):
            continue
        docstring = ast.get_docstring(node)
        if docstring is None:
            results.append((node.name, None))
        else:
            first_line = docstring.split("\n")[0].strip()
            results.append((node.name, first_line or None))

    return results


def main() -> int:
    """Entry point for the export-functions hook."""
    parser = argparse.ArgumentParser(
        description="Export public function reference to a markdown file.",
    )
    parser.add_argument(
        "--output-file",
        required=True,
        help="Path to the output file to write.",
    )
    parser.add_argument(
        "--source-root",
        required=True,
        help="Root package directory to scan recursively for Python source files.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        default=False,
        help="Fail if any public function is missing a docstring.",
    )
    args = parser.parse_args()

    output_file = Path(args.output_file)
    source_root = Path(args.source_root)

    if not source_root.is_dir():
        print(f"ERROR: Source root {source_root} is not a directory.", file=sys.stderr)
        return 1

    source_files = _collect_source_files(source_root)
    missing: list[tuple[Path, str]] = []
    bullets: list[str] = []

    for source_path in source_files:
        module = _module_name(source_path, source_root)

        for func_name, first_line in _get_public_functions(source_path):
            if first_line is None:
                missing.append((source_path, func_name))
                continue
            bullets.append(f"- `{func_name}()` (`{module}`) — {first_line}")

    content = "\n".join(bullets) + "\n"

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content, encoding="utf-8")

    print(f"Function reference written to {output_file}.")

    if args.strict and missing:
        print(
            f"ERROR: {len(missing)} public function(s) missing a docstring:",
            file=sys.stderr,
        )
        for path, name in missing:
            print(f"  - {name}() in {path}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
