name: Bump a Development Dependency
permissions: {}
on:
    workflow_dispatch:
        inputs:
            package:
                description: "Name of the package to bump"
                required: true
                type: choice
                # Hard-coding options for safety
                # It's also useful as a record of which packages tend to need bumping
                options:
                    - black
                    - urllib
jobs:
    regen:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  persist-credentials: false

            - name: Set up uv
              uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
              with:
                  version: "latest"
                  enable-cache: true

            - name: Regenerate
              # Updates uv.lock, requirements.txt, and docs/requirements.txt
              run: uv run -P $PKG_TO_BUMP prek -a uv-export
              env:
                  PKG_TO_BUMP: ${{ inputs.package }}
