name: Static Checks
permissions: {}
on:
    workflow_dispatch:
    push:
        branches: ["main"]
        paths-ignore:
            - "mkdocs.yml"
            - "AGENTS.md"
            - ".agents/**/*.md"
    pull_request:
        paths-ignore:
            - "mkdocs.yml"
            - "AGENTS.md"
            - ".agents/**/*.md"
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    analyze:
        name: Analyze
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout code
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
              with:
                  persist-credentials: false

            - name: Setup git user config
              run: |
                  git config --global user.name placeholder
                  git config --global user.email placeholder@example.com

            - name: Set up uv
              uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
              with:
                  version: "latest"
                  enable-cache: true

            - name: Run checks
              run: |
                  uv run --frozen prek -a
                  uv run --frozen basedpyright
              env:
                  PREK_UV_SOURCE: github
