name: Static Checks
permissions: {}
on:
    workflow_dispatch:
    push:
        branches: ["main"]
    pull_request:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    analyze:
        name: Analyze
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  persist-credentials: false

            - name: Setup git user config
              run: |
                  git config --global user.name placeholder
                  git config --global user.email placeholder@example.com

            - name: Set up uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
              with:
                  version: "latest"
                  enable-cache: true

            - name: Run checks
              run: |
                  uv run --frozen prek -a
                  uv run --frozen basedpyright
              env:
                  PREK_UV_SOURCE: github
